

import { ShadowPreset, Gradient, BrowserFrame } from './types';

// IMPORTANT: This is a public beta key from Giphy.
// For production use, it's recommended to get your own key from https://developers.giphy.com/
export const GIPHY_API_KEY = 'zlxQLTsnhkp2ry4Y69urTgEAeAcx3lcY';

export const SHADOW_PRESETS: ShadowPreset[] = [
  { name: 'None', value: 'none' },
  { name: 'Soft', value: 'drop-shadow(0 10px 8px rgb(0 0 0 / 0.04)) drop-shadow(0 4px 3px rgb(0 0 0 / 0.1))' },
  { name: 'Glow', value: 'drop-shadow(0 0 15px rgb(99 102 241 / 0.4))' },
  { name: 'Sharp', value: 'drop-shadow(6px 6px 0px rgb(0 0 0 / 0.8))' },
];

export const GRADIENT_PRESETS: Gradient[] = [
    { start: "#f6d365", end: "#fda085", angle: 145 },
    { start: "#fbc2eb", end: "#a6c1ee", angle: 145 },
    { start: "#84fab0", end: "#8fd3f4", angle: 145 },
    { start: "#a1c4fd", end: "#c2e9fb", angle: 145 },
    { start: "#d4fc79", end: "#96e6a1", angle: 145 },
    { start: "#89f7fe", end: "#66a6ff", angle: 145 },
    { start: "#ff9a9e", end: "#fecfef", angle: 145 },
    { start: "#fdfbfb", end: "#ebedee", angle: 145 },
    { start: "#e0c3fc", end: "#8ec5fc", angle: 145 },
    { start: "#4facfe", end: "#00f2fe", angle: 145 },
    { start: "#43e97b", end: "#38f9d7", angle: 145 },
    { start: "#fa709a", end: "#fee140", angle: 145 },
    { start: "#6237a1", end: "#21034a", angle: 145 },
    { start: "#09203f", end: "#537895", angle: 145 },
    { start: "#ff758c", end: "#ff7eb3", angle: 145 },
    { start: "#f093fb", end: "#f5576c", angle: 145 },
    { start: "#48c6ef", end: "#6f86d6", angle: 145 },
    { start: "#a3bded", end: "#6991c7", angle: 145 },
    { start: "#f5f7fa", end: "#c3cfe2", angle: 145 },
    { start: "#f1a7f1", end: "#fad0c4", angle: 145 },
    { start: "#30cfd0", end: "#330867", angle: 145 },
    { start: "#fdfcfb", end: "#e2d1c3", angle: 145 },
    { start: "#c1dfc4", end: "#deecdd", angle: 145 },
    { start: "#deecdd", end: "#c1dfc4", angle: 145 },
    { start: "#1e3c72", end: "#2a5298", angle: 145 },
    { start: "#21D4FD", end: "#B721FF", angle: 145 },
    { start: "#37ecba", end: "#72afd3", angle: 145 },
    { start: "#ff7e5f", end: "#feb47b", angle: 145 },
    { start: "#6a11cb", end: "#2575fc", angle: 145 },
    { start: "#ec4899", end: "#f43f5e", angle: 145 },
    { start: "#0ea5e9", end: "#22d3ee", angle: 145 },
    { start: "#f97316", end: "#fde047", angle: 145 },
    { start: "#8b5cf6", end: "#d946ef", angle: 145 },
    { start: "#16a34a", end: "#caB533", angle: 145 },
    { start: "#0f172a", end: "#334155", angle: 145 },
    { start: "#ffffff", end: "#e5e7eb", angle: 145 },
];

export const BROWSER_FRAMES: BrowserFrame[] = [
  { type: 'none', name: 'None', classNames: { header: '', body: '' } },
  { type: 'light', name: 'Light', classNames: { header: 'bg-gray-200 border-b border-gray-300', body: '' } },
  { type: 'dark', name: 'Dark', classNames: { header: 'bg-gray-800 border-b border-gray-700', body: '' } },
  { type: 'dark-solid', name: 'Dark Solid', classNames: { header: 'bg-slate-800', body: '' } },
  { type: 'yellow', name: 'Sunset', classNames: { header: 'bg-yellow-200 border-b border-yellow-300', body: '' } },
  { type: 'green', name: 'Mint', classNames: { header: 'bg-green-200 border-b border-green-300', body: '' } },
  { type: 'purple', name: 'Lavender', classNames: { header: 'bg-purple-200 border-b border-purple-300', body: '' } },
  { type: 'ocean', name: 'Ocean', classNames: { header: 'bg-blue-200 border-b border-blue-300', body: '' } },
];


export const EMOJI_DATA = [
  { emoji: '😀', name: 'Grinning Face', keywords: ['happy', 'joy', 'smile'] },
  { emoji: '😂', name: 'Face with Tears of Joy', keywords: ['happy', 'joy', 'laugh', 'tear'] },
  { emoji: '😍', name: 'Smiling Face with Heart-Eyes', keywords: ['love', 'crush', 'heart'] },
  { emoji: '🤔', name: 'Thinking Face', keywords: ['thinking', 'idea', 'ponder'] },
  { emoji: '🔥', name: 'Fire', keywords: ['hot', 'lit', 'flame'] },
  { emoji: '👍', name: 'Thumbs Up', keywords: ['approve', 'ok', 'like'] },
  { emoji: '❤️', name: 'Red Heart', keywords: ['love', 'like', 'heart'] },
  { emoji: '🚀', name: 'Rocket', keywords: ['launch', 'ship', 'space'] },
  { emoji: '🎉', name: 'Party Popper', keywords: ['celebration', 'party', 'tada'] },
  { emoji: '💡', name: 'Light Bulb', keywords: ['idea', 'light', 'thought'] },
  { emoji: '💻', name: 'Laptop', keywords: ['computer', 'tech', 'work'] },
  { emoji: '✨', name: 'Sparkles', keywords: ['stars', 'shiny', 'magic'] },
  { emoji: '💯', name: 'Hundred Points', keywords: ['score', 'perfect', '100'] },
  { emoji: '🙏', name: 'Folded Hands', keywords: ['please', 'pray', 'thanks'] },
  { emoji: '🤯', name: 'Exploding Head', keywords: ['mind blown', 'shocked', 'amazed'] },
  { emoji: '😎', name: 'Smiling Face with Sunglasses', keywords: ['cool', 'sunglasses', 'bright'] },
  { emoji: '😭', name: 'Loudly Crying Face', keywords: ['sad', 'cry', 'tear'] },
  { emoji: '🥳', name: 'Partying Face', keywords: ['celebration', 'party', 'hat'] },
  { emoji: '😊', name: 'Smiling Face with Smiling Eyes', keywords: ['happy', 'blush', 'proud'] },
  { emoji: '🥺', name: 'Pleading Face', keywords: ['begging', 'puppy eyes', 'sad'] },
  { emoji: '🤡', name: 'Clown Face', keywords: ['clown', 'fool', 'joke'] },
  { emoji: '🤖', name: 'Robot', keywords: ['bot', 'android', 'tech'] },
  { emoji: '💀', name: 'Skull', keywords: ['dead', 'death', 'skeleton'] },
  { emoji: '🌟', name: 'Glowing Star', keywords: ['star', 'glow', 'shiny'] },
  { emoji: '👋', name: 'Waving Hand', keywords: ['hello', 'bye', 'wave'] },
  { emoji: '👌', name: 'OK Hand', keywords: ['ok', 'perfect', 'good'] },
  { emoji: '💰', name: 'Money Bag', keywords: ['money', 'cash', 'rich'] },
  { emoji: '✅', name: 'Check Mark Button', keywords: ['done', 'correct', 'ok'] },
  { emoji: '❌', name: 'Cross Mark', keywords: ['wrong', 'no', 'cancel'] },
  { emoji: '❓', 'name': 'Question Mark', keywords: ['help', 'what', 'question'] },
  { emoji: '❗', name: 'Exclamation Mark', keywords: ['wow', 'surprise', 'warning'] },
  { emoji: '🧠', name: 'Brain', keywords: ['mind', 'smart', 'idea'] },
  { emoji: '💪', name: 'Flexed Biceps', keywords: ['strong', 'muscle', 'gym'] },
  { emoji: '👀', name: 'Eyes', keywords: ['look', 'see', 'watch'] },
  { emoji: '🙌', name: 'Raising Hands', keywords: ['praise', 'hooray', 'celebrate'] },
  { emoji: '🍕', name: 'Pizza', keywords: ['food', 'pepperoni', 'cheese'] },
  { emoji: '🍔', name: 'Hamburger', keywords: ['food', 'burger', 'fast food'] },
  { emoji: '🍟', name: 'French Fries', keywords: ['food', 'chips', 'fast food'] },
  { emoji: '⚽', name: 'Soccer Ball', keywords: ['football', 'sport', 'game'] },
  { emoji: '🏀', name: 'Basketball', keywords: ['ball', 'sport', 'game'] },
  { emoji: '🎮', name: 'Video Game', keywords: ['controller', 'play', 'game'] },
  { emoji: '🎯', name: 'Direct Hit', keywords: ['target', 'bullseye', 'darts'] },
  { emoji: '🎲', name: 'Game Die', keywords: ['dice', 'luck', 'random'] },
  { emoji: '🎵', name: 'Musical Note', keywords: ['music', 'song', 'sound'] },
  { emoji: '🎸', name: 'Guitar', keywords: ['music', 'instrument', 'rock'] },
  { emoji: '🎹', name: 'Musical Keyboard', keywords: ['piano', 'music', 'instrument'] },
  { emoji: '📱', name: 'Mobile Phone', keywords: ['phone', 'cell', 'iphone'] },
  { emoji: '✉️', name: 'Envelope', keywords: ['email', 'mail', 'letter'] },
  { emoji: '💵', name: 'Dollar Banknote', keywords: ['money', 'cash', 'bill'] },
];

export const INITIAL_STATE: import('./types').EditorState = {
  screenshot: undefined,
  imageDimensions: { width: 0, height: 0 },
  background: {
    type: 'gradient',
    value: GRADIENT_PRESETS[0],
  },
  padding: 64,
  cornerRadius: 24,
  shadow: SHADOW_PRESETS[1].value,
  textOverlays: [],
  emojiOverlays: [],
  gifOverlays: [],
  frame: BROWSER_FRAMES[0],
  user: null,
};